version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: productos_db
    environment:
      POSTGRES_DB: productos_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - productos_network

  # Aplicación NestJS
  api:
    build: .
    container_name: productos_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=productos_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password123
    depends_on:
      - postgres
    networks:
      - productos_network

volumes:
  postgres_data:

networks:
  productos_network:
    driver: bridge